CREATE TABLE IF NOT EXISTS hotels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  destination_id uuid,
  category_id uuid,
  name varchar NOT NULL,
  slug varchar UNIQUE,
  description text,
  short_description varchar,
  address varchar,
  province varchar,
  country varchar,
  postal_code varchar,
  contact_phone varchar,
  contact_email varchar,
  latitude decimal(10,7),
  longitude decimal(10,7),
  rating decimal(3,2),
  review_count integer DEFAULT 0,
  star_rating integer,
  status varchar DEFAULT 'draft',
  check_in_time varchar,
  check_out_time varchar,
  created_at timestamp,
  updated_at timestamp,
  deleted_at timestamp
);
