CREATE TABLE IF NOT EXISTS bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_number varchar UNIQUE,
  user_id uuid REFERENCES users (id),
  hotel_id uuid REFERENCES hotels (id),
  room_type_id uuid NOT NULL REFERENCES room_types (id),
  promotion_id uuid REFERENCES promotions (id),
  check_in date NOT NULL,
  check_out date NOT NULL,
  nights integer,
  adult_count integer NOT NULL DEFAULT 0,
  child_count integer DEFAULT 0,
  has_pet boolean DEFAULT false,
  has_car boolean DEFAULT false,
  room_count integer NOT NULL DEFAULT 1,
  contact_first_name varchar,
  contact_last_name varchar,
  contact_email varchar,
  contact_phone varchar,
  special_requests text,
  currency_code varchar DEFAULT 'THB',
  total_price decimal(10,2),
  subtotal_amount decimal(10,2),
  tax_amount decimal(10,2),
  service_fee_amount decimal(10,2),
  discount_amount decimal(10,2),
  final_price decimal(10,2),
  status varchar DEFAULT 'pending',
  payment_status varchar DEFAULT 'pending',
  payment_option varchar,
  confirmed_at timestamp,
  cancelled_at timestamp,
  cancel_reason varchar,
  completed_at timestamp,
  created_at timestamp,
  updated_at timestamp
);