CREATE TABLE IF NOT EXISTS payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES bookings (id),
  payment_method_id uuid,
  payment_gateway_id uuid,
  payment_method varchar NOT NULL,
  amount decimal(10,2) NOT NULL,
  currency_code varchar DEFAULT 'THB',
  payment_status varchar NOT NULL DEFAULT 'pending',
  transaction_ref varchar,
  gateway_transaction_id varchar,
  payment_intent_ref varchar,
  client_secret varchar,
  redirect_url varchar,
  qr_code_url text,
  failed_at timestamp,
  failure_reason varchar,
  expired_at timestamp,
  paid_at timestamp,
  refunded_amount decimal(10,2) DEFAULT 0,
  refunded_at timestamp,
  created_at timestamp,
  updated_at timestamp
);
